### ISSUE TITLE
abuild: checkdepends not installed

### ISSUE THREAD

**Issue by george-hopkins** [postmarketOS/pmbootstrap#1528] opened 2018-06-01 11:26 UTC
When building packages, the `checkdepends` directive is not taken into account. According to the Alpine Linux wiki, the feature should be available for versions >=3.6. I'm not very familiar with the code base so this might be resolved automatically at some time in the future.

At the moment only libdrm is using this feature.

Example:
```apkbuild
pkgname=checkdeptest
pkgver=0.1
pkgrel=0
pkgdesc="Test"
url="http://www.example.com"
arch="all"
license="GPL-3.0+"
depends=""
makedepends=""
checkdepends="nano"
source=""
builddir="$srcdir"

build () {
    true
}

check() {
    which nano
}

package() {
    true
}

sha512sums=""
```

**Comment by ollieparanoid** [comment] 2018-06-01 18:07
`abuild` is at version `3.2` right now: https://pkgs.alpinelinux.org/packages?name=abuild&branch=edge

But anyway, when running `pmbootstrap build --strict checkdepends` to let `abuild` resolve the dependencies, it installs `nano` correctly in your example. The problem is that we don't look at the `checkdepends` when resolving the dependencies with pmbootstrap.

I haven't tested this yet, but it should be possible to fix this by adding `checkdepends` [here](https://github.com/postmarketOS/pmbootstrap/blob/08951548f6278906d82221abdf2874f6618c2eb4/pmb/build/_package.py#L101) and [here](https://github.com/postmarketOS/pmbootstrap/blob/08951548f6278906d82221abdf2874f6618c2eb4/pmb/config/__init__.py#L188). Would you like to try this and make a PR?

Thank you very much for this detailed bug report!

**Closed** 2018-06-04 19:07 UTC
Labels: bug, pmbootstrap
