### ISSUE TITLE
apk build fails and unsigned APKINDEX.tar.gz file

### ISSUE THREAD

**Issue by beckerichmika** [postmarketOS/pmbootstrap#2] opened 2017-05-27 13:32 UTC
I'm experiencing issues at a specific part of the build:
`[14:57:15] *** (2/5) CREATE DEVICE ROOTFS (lge-d855) ***
[14:57:15] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
[sudo] Passwort für mika: 
[14:57:19] ERROR: Command failed: (native) % apk --no-progress add qemu-user-static-repack qemu-user-static-repack-binfmt
[14:57:19] Run 'pmbootstrap log' for details.
`

In pmbootstrap log I found some errors:
`(007850) [14:58:56] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
(007850) [14:58:56] (native) % apk --no-progress add qemu-user-static-repack qemu-user-static-repack-binfmt
WARNING: Ignoring /home/user/packages/user/x86_64/APKINDEX.tar.gz: UNTRUSTED signature
ERROR: unsatisfiable constraints:
  qemu-user-static-repack (missing):
    required by: world[qemu-user-static-repack]
  qemu-user-static-repack-binfmt (missing):
    required by:
                 world[qemu-user-static-repack-binfmt]
(007850) [14:58:57] ERROR: Command failed: (native) % apk --no-progress add qemu-user-static-repack qemu-user-static-repack-binfmt
(007850) [14:58:57] Run 'pmbootstrap log' for details.`

I searched for a solution to sign the APKINDEX.tar.gz file so I started the chroot and followed this tutorial under "Testing the unsigned repository": https://engineering.fundingcircle.com/blog/2015/04/28/create-alpine-linux-repository/ . This resolved the issue, but it needs to be fixed in the script.

**Comment by ollieparanoid** [comment] 2017-05-27 13:35
Have you typed in your user's password, where it says:
`[sudo] Passwort für mika:`

Because if you do not, it will run into a timeout and the command will simply fail. I know, this isn't very intuitive and needs to be worked on, sorry.

Can you please run `pmbootstrap zap` (to remove the non-working chroot) and try it again?

**Comment by beckerichmika** [comment] 2017-05-27 13:42
I typed it in, that's surely not the problem, but I'll try the zap command.
I ran the command and reran the pmbootstrap install command and starts building. Weird. I didn't even need to sign the APKINDEX.tar.gz file, even if I removed all the chroots.
` $ ./pmbootstrap.py install
[15:40:17] *** (1/5) PREPARE NATIVE CHROOT ***
[15:40:17] (native) install alpine-base
[15:40:19] (native) install cryptsetup util-linux e2fsprogs parted
[15:40:19] *** (2/5) CREATE DEVICE ROOTFS (lge-d855) ***
[15:40:20] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
[15:40:21] Register qemu binfmt (arm)
[15:40:21] (rootfs_lge-d855) install alpine-base
[15:40:26] (buildroot_armhf) install alpine-base
[15:40:30] (buildroot_armhf) install abuild build-base ccache
[15:40:36] (buildroot_armhf) install linux-headers
[15:40:38] (native) install abuild build-base ccache
[15:40:44] (native) install gcc g++ paxmark bison flex texinfo gawk zip gmp-dev mpfr-dev mpc1-dev zlib-dev linux-headers gmp-dev mpfr-dev mpc1-dev isl-dev zlib-dev musl-dev-armhf binutils-armhf
[15:40:45] (native) build x86_64/gcc-armhf-6.3.0-r4.apk

`

**Comment by ollieparanoid** [comment] 2017-05-27 13:52
That is strange indeed. But I'm glad, that it works now!
Maybe it was related to #1, where the user generated signing keys did not get copied properly.
I'll close this, because it can't be reproduced by either of us right now.

**Closed by ollieparanoid** 2017-05-27 13:52 UTC
