### ISSUE TITLE
Timestamp based build: ambiguous argument

### ISSUE THREAD

**Issue by antonok-edm** [postmarketOS/pmbootstrap#151] opened 2017-07-14 20:48 UTC
When running `pmbootstrap.py build linux-asus-grouper --arch=armhf --force`, I get the following error

```
fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
from the command `git diff --name-only origin`

My local repository was set up with the following commands:
```
git clone https://github.com/postmarketOS/pmbootstrap
git remote rename origin upstream
git remote add origin https://github.com/antonok-edm/pmbootstrap
```

**Comment by ollieparanoid** [comment] 2017-07-17 16:04
I can *not* reproduce this with `git version 2.13.3`:
```shell
% rm ~/.config/pmbootstrap.cfg
% mkdir -p /tmp/test
% cd /tmp/test
% git clone https://github.com/postmarketOS/pmbootstrap
% cd pmbootstrap
% git remote add origin https://github.com/antonok-edm/pmbootstrap
fatal: remote origin already exists.
% git remote rename origin upstream
% git remote add origin https://github.com/antonok-edm/pmbootstrap
% ./pmbootstrap build --force hello-world
# works without crashing, although timestamp based rebuilds are enabled
```

Follow-up questions:
* Which git version do you have?
* Is there maybe another command I need to run to reproduce this bug? 
pushing/pulling/checking out a branch?
* "Ambiguous argument" means, that origin has multiple meanings for git in this context, as I understand it. so maybe the renaming has not worked for some reason?
* Can you reproduce the bug yourself by running the commands as listed above?
* (Maybe another aports folder got used (if you have checked out the code in another location earlier and ran `./pmbootstrap.py init` from there - make sure to delete the `pmbootstrap.cfg` as shown above).)

Thanks for making this bug report!

**Comment by antonok-edm** [comment] 2017-07-19 00:47
* Git version 2.11.0
* Really couldn't find any other commands that would have been out of the ordinary.
* Renaming has worked, I can use `origin` as a valid remote name for other git commands.
* Can't reproduce in a new repo, unfortunately, but it still happens on my existing one after several commits and pulls.
* Nope, not the case.

I have discovered that entering the offending command manually
`git diff origin --name-only`
results in the same error.

I think the "ambiguity" is coming from `git` not being able to tell if `origin` is a revision or a file.
As far as I understand git, `origin` is a remote, not a revision or file. Regardless, I tried using `--` as a separator...

`git diff --name-only origin --`
results in
`fatal: bad revision 'origin'`

whereas
`git diff --name-only -- origin`
succeeds and presents an empty diff.

**Comment by ollieparanoid** [comment] 2017-07-19 16:21
Yep, `origin` is a remote, and not a revision or file.

Nevertheless I have tried to change the command to `git diff --name-only -- origin` in the code and ran the [test case](https://github.com/postmarketOS/pmbootstrap/blob/1aae094b500515b1a296d9b1f493760dcd5d4e4c/test/test_aport_in_sync_with_git.py#L84). But it complains, that the output is always empty and the mechanism does not work anymore (which makes sense, because there is no `origin` file).

Closing this, because we both can not reproduce it. Please start with a new git folder, where this does not happen. We will of course re-open this, if it happens again (and we hopefully *can* reproduce it).

Thank you for all the information you have provided!

**Comment by ollieparanoid** [comment] 2017-08-07 23:18
This bug happened to @rendeko, and he posted the following log. Maybe we can make sense of this now, thanks!
https://pastebin.com/us13FgmD

**Comment by drebrez** [comment] 2017-08-08 00:31
I also have the same problem, here is the log: https://pastebin.com/KuxfN6Rc
git version 2.7.4
```
$ git remote -v
drebrez https://github.com/drebrez/pmbootstrap.git (fetch)
drebrez https://github.com/drebrez/pmbootstrap.git (push)
origin  https://github.com/postmarketOS/pmbootstrap.git (fetch)
origin  https://github.com/postmarketOS/pmbootstrap.git (push)
```

**Comment by ollieparanoid** [comment] 2017-08-08 17:00
Thank for reporting and posting the log!
The workaround is to disable *timestamp based rebuilds* in `pmbootstrap init`, I'll need to look more into this to fix it.

**Comment by drebrez** [comment] 2017-08-15 00:10
I think I solved it, when you rename a remote or you add it manually, the origin/HEAD ref doesn't exist, only when you clone it (https://stackoverflow.com/questions/17639383/how-to-add-missing-origin-head-in-git-repo).

I've solved doing this command:
`git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/master`

**Comment by ollieparanoid** [comment] 2017-08-15 14:12
Thanks @drebrez, that is super helpful \o/

I propose, that we catch whether the command returns the "ambiguous argument" message. And if it does, we ask if we should add the `symbolic-ref` like in your command above.

**Comment by drebrez** [comment] 2017-08-15 20:57
How it is supposed to work the timestamp based build feature? 
because with `git diff --name-only origin` seems to always do a diff of the current changes against the latest master branch, is it the correct behavior?
If you are working on a branch which is not based on the latest master you always get differences, it means that it will always rebuild something?

**Comment by ollieparanoid** [comment] 2017-08-16 17:33
Thanks for asking, this is a quite complex feature and it's good when someone else reviews it!

So it will rebuild when a package, when all of these conditions are met:
* has the same version
* source files are out of sync with upstream
* files have a newer "last modified" timestamp, than in the binary package

The full list of conditions can be found [here](https://github.com/postmarketOS/pmbootstrap/blob/3800cd09f462233acb23334c2db16ae75fb60a38/pmb/build/other.py#L169) (should be easy to read with the comments).

I think this works as expected most of the time, one example use case:
* user A changes package A in feature-branch
* user B builds package A in master
* user B pulls the source
* user B switches to feature-branch (files from package A get a newer last modified timestamp, and they are not the same as in master)
* user B runs pmbootstrap install, the package gets re-built

...now that I'm writing this, I think I missed the following case:
* (same steps from use case above)
* user B checks out master again
* user B runs pmbootstrap install, the user should get a warning, that the timestamp of the binary package is higher than the last modified timestamps of the files


Please tell me when you see a better option or find an use case (except for the one above, I'll create a ticket for that soon) where it does not work or if I missed something else.

**Closed** 2017-09-25 22:05 UTC
Labels: bug, pmbootstrap
