### ISSUE TITLE
[rx51] Sometimes the phone boots without usable display

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#208] opened 2017-07-20 16:47 UTC
Sometimes the phone doesn't boot right and you only see scrolling lines on the display:

![lines](https://user-images.githubusercontent.com/6928199/28429082-bbac110a-6d7b-11e7-8418-7e89168f1afa.jpg)

This has been reproduced by @craftyguy

**Comment by craftyguy** [comment] 2017-07-20 16:49
This is almost certainly related to the issue reported here: https://lkml.org/lkml/2017/6/14/901

Unfortunately it doesn't look like the 'fix' (reverting one patch and applying a new one from drm-next) have been staged for 4.13. I may produce a patch that we can apply to the kernel in the linux-nokia-rx51 APKBUILD..

**Comment by ollieparanoid** [comment] 2017-07-20 17:13
If you can't get it fixed, I suggest reaching out to the kernel devs working on the N900 patches.

**Comment by craftyguy** [comment] 2017-07-20 17:14
I agree. I am building 4.13-rc1 right now to test it to see if it's still there. They'll also want me to try to reproduce this with the drm-next branch before they'll talk to me (I highly suspect!).

**Comment by craftyguy** [comment] 2017-07-21 01:35
I sent a response to that thread on the linux-kernel mailing list asking if there was any update. None of the patches in 4.13 for omap-drm seem to mention this problem specifically in the rather short commit messages, and 4.13-rc1 showed the exact same issue so I suspect it hasn't been resolved yet.

**Comment by craftyguy** [comment] 2017-07-21 22:18
I noticed that if I compile gpio_keys into the kernel instead of as a LKM, this problem seems to happen 100% of the time on every boot.

**Comment by craftyguy** [comment] 2017-07-31 23:32
#309, via d6bf000, works around this issue by applying a patch to linux-postmarketos.

**Comment by craftyguy** [comment] 2017-10-12 23:52
Looks like the patch to fix this issue ([seen here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/gpu/drm/omapdrm/omap_drv.c?id=fc5cc9678e130196012c17b37e555d53d3d3476b)) has been merged into 4.14!

**Comment by ollieparanoid** [comment] 2017-11-18 14:23
Fixed in kernel 4.14 (#903).

**Closed by ollieparanoid** 2017-11-18 14:23 UTC
Labels: bug, device, upstream
