### ISSUE TITLE
Can't write to packages folder: /home/pmos/packages//pmos

### ISSUE THREAD

**Issue by MoreRobustThanYou** [postmarketOS/pmbootstrap#959] opened 2017-11-30 21:42 UTC
Which causes a permission denied error.

**Comment by ollieparanoid** [comment] 2017-11-30 21:48
Thanks for opening the issue. What do you mean with "outputs" - could you attach a log?

**Comment by MoreRobustThanYou** [comment] 2017-12-01 00:06
kwayland also does this, log: 
```
[ 92%] Built target testWaylandSeat
[ 93%] Built target testContrast
[ 94%] Built target testWaylandRegistry
[ 94%] Built target testWindowmanagement
[ 95%] Built target testWaylandOutputManagement
[ 96%] Built target testSubCompositor
[ 96%] Built target testCompositor
[ 97%] Built target testSubSurface
[ 97%] Built target testBlur
[ 97%] Built target testDataSource
[ 97%] Built target testSlide
[ 98%] Built target testDataDevice
[ 99%] Built target testServerSideDecoration
[ 99%] Built target testPointerConstraints
[ 99%] Built target testWaylandServerSeat
[ 99%] Built target testQtSurfaceExtension
[ 99%] Built target testNoXdgRuntimeDir
[ 99%] Built target testWaylandServerDisplay
[100%] Built target testRenderingServer
Install the project...
-- Install configuration: "Release"
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/cmake/KF5Wayland/KF5WaylandQchTargets.cmake
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/cmake/KF5Wayland/KF5WaylandConfig.cmake
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/cmake/KF5Wayland/KF5WaylandConfigVersion.cmake
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/cmake/KF5Wayland/KF5WaylandTargets.cmake
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/cmake/KF5Wayland/KF5WaylandTargets-release.cmake
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/kwayland_version.h
-- Installing: /home/pmos/build/pkg/kwayland/etc/xdg/org_kde_kwayland.categories
-- Installing: /home/pmos/build/pkg/kwayland/usr/share/doc/qt5/KF5Wayland.qch
-- Installing: /home/pmos/build/pkg/kwayland/usr/share/doc/qt5/KF5Wayland.tags
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/libKF5WaylandClient.so.5.40.0
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/libKF5WaylandClient.so.5
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/libKF5WaylandClient.so
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/kwaylandclient_export.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/blur.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/buffer.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/compositor.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/connection_thread.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/contrast.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/event_queue.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/datadevice.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/datadevicemanager.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/dataoffer.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/datasource.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/dpms.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/fakeinput.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/fullscreen_shell.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/idle.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/keyboard.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/outputconfiguration.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/outputmanagement.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/outputdevice.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/output.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/pointer.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/pointerconstraints.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/plasmashell.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/plasmawindowmanagement.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/plasmawindowmodel.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/pointergestures.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/region.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/registry.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/relativepointer.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/seat.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/server_decoration.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/shadow.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/shell.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/shm_pool.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/slide.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/subcompositor.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/subsurface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/surface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/touch.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/textinput.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/xdgshell.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Client/xdgforeign_v2.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/libKF5WaylandServer.so.5.40.0
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/libKF5WaylandServer.so.5
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/libKF5WaylandServer.so
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/kwaylandserver_export.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/blur_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/contrast_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/buffer_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/clientconnection.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/compositor_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/datadevice_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/datadevicemanager_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/dataoffer_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/datasource_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/display.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/dpms_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/fakeinput_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/global.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/idle_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/keyboard_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/outputdevice_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/outputchangeset.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/outputconfiguration_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/outputmanagement_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/output_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/pointer_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/pointerconstraints_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/pointergestures_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/plasmashell_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/plasmawindowmanagement_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/qtsurfaceextension_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/region_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/relativepointer_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/resource.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/seat_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/server_decoration_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/shadow_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/shell_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/slide_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/subcompositor_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/surface_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/textinput_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/touch_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/xdgshell_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/include/KF5/KWayland/Server/xdgforeign_interface.h
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri
-- Installing: /home/pmos/build/pkg/kwayland/usr/lib/org-kde-kf5-kwayland-testserver
-- Set runtime path of "/home/pmos/build/pkg/kwayland/usr/lib/org-kde-kf5-kwayland-testserver" to ""
>>> kwayland-dev*: Running split function dev...
>>> kwayland-dev*: Preparing subpackage kwayland-dev...
>>> kwayland-dev*: Stripping binaries
/usr/bin/abuild: line 2544: git: not found
/usr/bin/abuild: line 2544: git: not found
>>> kwayland-dev*: Running postcheck for kwayland-dev
>>> kwayland-doc*: Running split function doc...
>>> kwayland-doc*: Preparing subpackage kwayland-doc...
/usr/bin/abuild: line 2544: git: not found
/usr/bin/abuild: line 2544: git: not found
>>> kwayland-doc*: Running postcheck for kwayland-doc
>>> kwayland*: Running postcheck for kwayland
>>> kwayland*: Preparing package kwayland...
>>> kwayland*: Stripping binaries
/usr/bin/abuild: line 2544: git: not found
/usr/bin/abuild: line 2544: git: not found
>>> kwayland-dev*: Scanning shared objects
>>> kwayland-doc*: Scanning shared objects
>>> kwayland*: Scanning shared objects
>>> kwayland-dev*: Tracing dependencies...
	qt5-qtbase-dev
	wayland-dev
	kwayland=5.40.0-r0
>>> kwayland-dev*: Package size: 812.0 KB
>>> kwayland-dev*: Compressing data...
>>> kwayland-dev*: Create checksum...
>>> kwayland-dev*: Create kwayland-dev-5.40.0-r0.apk
/usr/bin/abuild: line 2544: can't create /home/pmos/packages//pmos/armhf/kwayland-dev-5.40.0-r0.apk: Permission denied
>>> ERROR: kwayland*: create_apks failed
>>> ERROR: kwayland: all failed
(017211) [16:53:46] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(017211) [16:53:46] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/steamport/.local/var/pmbootstrap/log.txt
(017211) [16:53:46] ERROR: Command failed: (buildroot_armhf) % cd /home/pmos/build && su pmos -c 'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
(017211) [16:53:46] Run 'pmbootstrap log' for details.
(017211) [16:53:46] See also: <https://postmarketos.org/troubleshooting>
(017211) [16:53:46] Traceback (most recent call last):
  File "/home/steamport/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', 'env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/steamport/.local/var/pmbootstrap/chroot_buildroot_armhf sh -c \'cd /home/pmos/build;su pmos -c \'"\'"\'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d\'"\'"\'\'']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/steamport/pmbootstrap/pmb/__init__.py", line 57, in main
    getattr(frontend, args.action)(args)
  File "/home/steamport/pmbootstrap/pmb/helpers/frontend.py", line 201, in install
    pmb.install.install(args)
  File "/home/steamport/pmbootstrap/pmb/install/install.py", line 307, in install
    pmb.build.package(args, pkgname, args.deviceinfo["arch"])
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 282, in package
    skip_init_buildenv):
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 147, in init_buildenv
    depends, built = build_depends(args, apkbuild, arch, strict)
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 103, in build_depends
    if package(args, depend, arch, strict=strict):
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 282, in package
    skip_init_buildenv):
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 147, in init_buildenv
    depends, built = build_depends(args, apkbuild, arch, strict)
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 103, in build_depends
    if package(args, depend, arch, strict=strict):
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 282, in package
    skip_init_buildenv):
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 147, in init_buildenv
    depends, built = build_depends(args, apkbuild, arch, strict)
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 103, in build_depends
    if package(args, depend, arch, strict=strict):
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 287, in package
    suffix)
  File "/home/steamport/pmbootstrap/pmb/build/_package.py", line 220, in run_abuild
    pmb.chroot.user(args, cmd, suffix, "/home/pmos/build")
  File "/home/steamport/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/steamport/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/steamport/pmbootstrap/pmb/helpers/run.py", line 66, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (buildroot_armhf) % cd /home/pmos/build && su pmos -c 'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
```

**Comment by PureTryOut** [comment] 2017-12-01 08:41
I can't reproduce this locally (on the latest Git), and I don't think it's related to the APKBUILD itself. Could you try removing the pmbootstrap directory (`~/.local/var/pmbootstrap`) entirely and rerunning `./pmbootstrap.py init` and all other commands? You will need root access to do this.

**Comment by ollieparanoid** [comment] 2017-12-01 19:23
Make sure to run `pmbootstrap shutdown` before removing your work folder though.

Whenever you compile a package with `pmbootstrap`, it gets written to `/home/pmos/packages/pmos/`, which gets set up as symbolic link to `/mnt/pmbootstrap-packages` when initializing the chroot for building. The `packages` folder in your work folder gets mounted to `/mnt/pmbootstrap-packages` inside the chroots. I guess the symlink is missing, or there's a permission problem with your packages folder.

So it should get resolved by removing the work folder completely, as @PureTryOut suggested.

**Comment by MoreRobustThanYou** [comment] 2017-12-01 20:29
Ok, that fixed this. However, I would recommend adding a check to make sure the symlink is a symlink... and not a file.

**Closed** 2017-12-01 20:29 UTC
Labels: bug, pmbootstrap

**Comment by ollieparanoid** [comment] 2017-12-02 08:09
That sounds like a good idea. But I don't understand yet how there was a file instead of a symlink in your case. I would recommend that we add the check if this happens again for someone. I'm glad that it's resolved for you @MoreRobustThanYou!
