### ISSUE TITLE
pmbootstrap: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#948] opened 2017-11-28 23:22 UTC
@z3ntu reported:
```
[16:55:49] *** (1/5) PREPARE NATIVE CHROOT ***
[16:55:49] (native) install alpine-base
[16:55:51] (native) install cryptsetup util-linux e2fsprogs parted
[16:55:51] *** (2/5) CREATE DEVICE ROOTFS ("fairphone-fp2") ***
[16:55:51] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
[16:55:52] Register qemu binfmt (arm)
[16:55:52] (rootfs_fairphone-fp2) install alpine-base
[16:56:00] ERROR: maximum recursion depth exceeded
[16:56:00] Run 'pmbootstrap log' for details.
[16:56:00] See also: <https://postmarketos.org/troubleshooting>
```
`pmbootstrap log`:
> https://pastebin.com/T37YkY70 and a whole lot of more of these lines 

@z3ntu:
* does this still happen after `pmbootstrap zap`?
* does this happen with [0.3.0](https://github.com/postmarketOS/pmbootstrap/releases/tag/0.3.0)?

**Comment by z3ntu** [comment] 2017-11-29 07:49
I git pull'ed before sending that message.
I ran zap at least two times, and also zap -m

**Comment by z3ntu** [comment] 2017-11-29 10:07
It also isn't fixed after (re)moving `~/.local/var/pmbootstrap`
BUT it's fixed by downgrading to v0.3.0

**Comment by z3ntu** [comment] 2017-11-29 16:32
Ah the issue is the package I have only locally: https://raw.githubusercontent.com/z3ntu/openrazer-alpine/master/APKBUILD
This apkbuild fails with the new parser (but works in normal alpine and with the old parser)

**Comment by ollieparanoid** [comment] 2017-11-29 18:49
Okay, `openrazer-kernel-modules-dkms` is in `subpackages` **and** `depends`, that explains it (it depends on itself)! You could fix this by using `install_if="$pkgname"` in `dkms()` and removing `openrazer-kernel-modules-dkms` from `depends`.

`pmbootstrap` should handle this better though, so let's leave this PR open until it's fixed there.

Part of the `APKBUILD` to reproduce it:
```shell
pkgname=openrazer-meta
pkgver=2.0.0
pkgrel=0
pkgdesc="OpenRazer"
url="https://openrazer.github.io"
arch="all"
license="GPL2"
depends="openrazer-kernel-modules-dkms openrazer-daemon py3-openrazer"
makedepends="python3"
install=""
subpackages="openrazer-kernel-modules-dkms openrazer-daemon py3-openrazer:py3"
# ...
```

**Comment by z3ntu** [comment] 2017-11-29 18:54
As it's working fine with abuild, I see no reason to change it (and that way the pmbootstrap parser has to handle that 😉)

**Comment by ollieparanoid** [comment] 2017-11-29 21:25
That's surprising, I didn't know that this is allowed in `abuild`. You're right, then `pmbootstrap` should handle it just like `abuild` does.

**Closed** 2017-12-02 11:51 UTC
Labels: bug, pmbootstrap

**Comment by z3ntu** [comment] 2017-12-02 12:54
Thanks!

**Comment by ollieparanoid** [comment] 2017-12-02 12:57
You're welcome! Thanks for reporting and confirming that the fix works :tada:
