### ISSUE TITLE
"-Werrors" not removed by prepare() in APKBUILD

### ISSUE THREAD

**Issue by ashirviskas** [postmarketOS/pmbootstrap#1124] opened 2018-01-15 22:32 UTC
I'm trying to build a kernel with gcc6 for Nextbit Robin and I'm getting tons of Werrors, mostly with messages about bad indentation.

Here's an example below:

`drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4768:4: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
    for (ptr = str; i_isspace(*ptr); ptr++);
    ^~~
`

I'm new to compiling kernels, so maybe I'm doing something wrong?

**Comment by ollieparanoid** [comment] 2018-01-16 19:58
In the `prepare()` of the `linux-` APKBUILD that has been generated should be the following:

```shell
# Remove -Werror from all makefiles
find . -type f -name Makefile -print0 | \
	xargs -0 sed -i 's/-Werror-/-W/g'
find . -type f -name Makefile -print0 | \
	xargs -0 sed -i 's/-Werror//g'
```

This changes `-Werror-*` to `-W*` and removes the `-Werror` flag completely for all `Makefiles`. If you have this, then for some reason it does not work with the kernel sources you have (they probably have specified the `-Werror` flag in another way which we don't catch).

To debug this, you could run the build once and let it fail, then enter the chroot and find the remaining Werror statement:
```shell
pmbootstrap chroot
cd /home/pmos/build/
grep . -r Werror
```

If you can't find it, we can also take a look if you could attach the `APKBUILD` to this issue.

**Comment by ashirviskas** [comment] 2018-01-16 20:02
Thank you for a quick response. Yes, those lines are present. 

After running those three lines I only get this:

`grep: Werror: No such file or directory`

**Comment by ollieparanoid** [comment] 2018-01-16 21:51
Sorry, I meant: `grep -r Werror .`
Making patches for the Werrors also kind of works, but usually there are many of them, and it's just much easier to disable all of them. (In my opinion it's not worth putting much energy in the kernel forks beyond of making them compile and work once, because they won't get updates from upstream anyway.)

**Comment by ashirviskas** [comment] 2018-01-16 23:45
It returns tons of text that is hardly readable for a newbie like me.

Here it is:

[errors.txt](https://github.com/postmarketOS/pmbootstrap/files/1637189/errors.txt)


I attached my archived linux-nextbit-robin folder below, with APKBUILD file included.
[linux-nextbit-robin.zip](https://github.com/postmarketOS/pmbootstrap/files/1637180/linux-nextbit-robin.zip)

**Comment by drebrez** [comment] 2018-01-17 00:20
@ashirviskas @ollieparanoid I think the problem is with the `sed` command which is not able to replace the `-Werror` in very long lines.
Ref: https://www.gnu.org/software/sed/manual/sed.html#Limitations

**Comment by drebrez** [comment] 2018-01-17 00:38
Ignore my last comment, in the error.txt are not even Makefiles them.
But maybe it's this one: https://github.com/LineageOS/android_kernel_nextbit_msm8992/blob/8b8773362248bdba3224a1d92e76c5b9004519d6/drivers/staging/qcacld-2.0/Kbuild#L980
or this:
https://github.com/LineageOS/android_kernel_nextbit_msm8992/blob/8b8773362248bdba3224a1d92e76c5b9004519d6/drivers/staging/usbip/userspace/configure.ac#L21

**Comment by ashirviskas** [comment] 2018-01-17 01:49
Thank you.

Applying a patch to the first file linked gets rid of Werrors (at least till the place where it gets other errors).

But then there are new errors. I guess I'm all by myself now?

However, if anyone has any ideas (because I don't), errors are these:

```
  CC      arch/arm64/kernel/setup.o
  CC      arch/arm64/kernel/signal.o
  CC      arch/arm64/kernel/sys.o
  CC      arch/arm64/kernel/stacktrace.o
  CC      arch/arm64/kernel/time.o
  CC      arch/arm64/kernel/traps.o
  CC      arch/arm64/kernel/io.o
  CC      arch/arm64/kernel/vdso.o
  AS      arch/arm64/kernel/hyp-stub.o
  CC      arch/arm64/kernel/psci.o
/tmp/ccEMGnkD.s: Assembler messages:
/tmp/ccEMGnkD.s:42: Error: .err encountered
/tmp/ccEMGnkD.s:43: Error: .err encountered
/tmp/ccEMGnkD.s:44: Error: .err encountered
/tmp/ccEMGnkD.s:103: Error: .err encountered
/tmp/ccEMGnkD.s:104: Error: .err encountered
/tmp/ccEMGnkD.s:105: Error: .err encountered
make[1]: *** [scripts/Makefile.build:309: arch/arm64/kernel/psci.o] Error 1
make: *** [Makefile:827: arch/arm64/kernel] Error 2
>>> ERROR: linux-nextbit-robin: all failed
(004518) [03:10:42] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ollieparanoid** [comment] 2018-01-17 17:59
> I guess I'm all by myself now?

No you're not, the pmOS community is there to help :wink: 

I've researched the error, and this patch seems to fix it (click on "raw" for the raw patch file): https://patchwork.kernel.org/patch/5697041/

> When compiling the kernel with very recent gcc-4.9 compilers we see the
> following errors:
>
>    /tmp/ccEayz7S.s: Assembler messages:
>    /tmp/ccEayz7S.s:41: Error: .err encountered
>    /tmp/ccEayz7S.s:42: Error: .err encountered
>    /tmp/ccEayz7S.s:43: Error: .err encountered
>    /tmp/ccEayz7S.s:101: Error: .err encountered
>    /tmp/ccEayz7S.s:102: Error: .err encountered
>    /tmp/ccEayz7S.s:103: Error: .err encountered
>
> This is due to assumptions about the register assignments made by gcc on
> function entry.  The errors above occur when these assignments are not
> as expected.  It turns out that when you enable mcount preables (-pg)
> these are altered and the compilation failed.

**Comment by ashirviskas** [comment] 2018-01-20 18:31
Thank you so much. I had a spare hour and tried to compile with this patch applied but I'm once again getting Werrors. This time it looks like this:

` CC      drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.o
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c: In function 'i_trim':
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4768:4: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
    for (ptr = str; i_isspace(*ptr); ptr++);
    ^~~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4769:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
       if (*ptr == '\0')
       ^~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4777:4: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
    for (; ptr != str && i_isspace(*ptr); ptr--);
    ^~~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4779:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
       ptr[1] = '\0';
       ^~~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c: In function 'hdd_update_config_dat':
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:6641:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
     if (ccmCfgSetInt(pHddCtx->hHal, WNI_CFG_MCAST_BCAST_FILTER_SETTING, pConfig->mcastBcastFilterSetting,
     ^~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:6652:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
      if (ccmCfgSetInt(pHddCtx->hHal, WNI_CFG_TELE_BCN_WAKEUP_EN, pConfig->teleBcnWakeupEn,
      ^~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:309: drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.o] Error 1
make[2]: *** [scripts/Makefile.build:455: drivers/staging/qcacld-2.0] Error 2
make[1]: *** [scripts/Makefile.build:455: drivers/staging] Error 2
make: *** [Makefile:827: drivers] Error 2
>>> ERROR: linux-nextbit-robin: all failed
(012155) [20:24:01] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

Maybe you can teach me identifying where those -Werrors are so the next time this happens I would be able to do it myself?

**Comment by ollieparanoid** [comment] 2018-01-20 19:01
In general, you can run grep on the extracted kernel source to find out which files have the Werror statements:
```shell
grep -r Werror .
```

However, it would be more effective to automatically replace it in all `Kbuild` files (just like we replace it already in all Makefiles). In fact I did that with your kernel, and it compiled fine.
Just modify the `prepare()` function in your `APKBUILD` as shown here:
https://github.com/postmarketOS/pmbootstrap/pull/1139/files

(When this PR gets accepted, this will be the new default.)

**Comment by ashirviskas** [comment] 2018-01-20 23:19
https://github.com/postmarketOS/pmbootstrap/pull/1145 :)


p.s. this is my first real pull request

**Comment by ollieparanoid** [comment] 2018-01-21 14:52
Thanks! Closing this issue now, it seems like everything is resolved now. :tada: 
If you have other problems/feature ideas etc, don't hesitate to open new issues. :+1:

**Closed by ollieparanoid** 2018-01-21 14:52 UTC
Labels: kernel, question
