### ISSUE TITLE
Porting Motorola Moto G 2014 "titan"

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#53] opened 2017-06-04 11:59 UTC
Hello.

I love your project and would like to contribute porting my Moto G 2014 device.

In addition to opening issues about minor bugs, I've also pushed the current work to my [device-motorola-titan branch](https://github.com/PabloCastellano/pmbootstrap/tree/device-motorola-titan) banch.

What's still missing?
- [ ] deviceinfo_flash_offset_base value
- [ ] kernel
- [ ] testing

According to [titan.yml](https://github.com/LineageOS/lineage_wiki/blob/master/_data/devices/titan.yml) this device is using [android_kernel_motorola_msm8226](https://github.com/LineageOS/android_kernel_motorola_msm8226) but since my lack of knowledge I don't know how to continue.

Any help is appreciated!

**Comment by PabloCastellano** [comment] 2017-06-04 12:14
`This script requires a shell more modern than all the shells that I found on your system. Please tell bug-autoconf@gnu.org about your system, including any error possibly output before this message. Then install a modern shell, or manually run the script under such a shell if you do have one.`

https://pastebin.com/nF2X22ea

**Comment by ollieparanoid** [comment] 2017-06-04 12:16
What is your host system?

**Comment by PabloCastellano** [comment] 2017-06-04 12:19
```
vermuth:~$ lsb_release -d
Description:	Linux Mint 17 Qiana
```

**Comment by ollieparanoid** [comment] 2017-06-04 12:28
You have tried building with `pmbootstrap build linux-motorola-titan` first, right?
Looks like device nodes are missing in your chroot. As suggested in #52: try to zap your chroot and re-create it (`pmbootstrap chroot` will re-create it). pay attention to whether the device nodes get created correctly in the log.

**Comment by ollieparanoid** [comment] 2017-06-04 12:30
`CARCH=x86_64 abuild -d` <- this is not how it should be done, the dependency resolving should be done with pmbootstrap

**Comment by PabloCastellano** [comment] 2017-06-04 17:36
JFTR: I changed the chroot directory and the issue that was preventing me from building binutils went away

**Comment by lawl** [comment] 2017-06-04 17:46
So this is an issue with ecryptfs. Should probably file a bug on ecryptfs and maybe add a message to pmbootstrap if it detects it. An easy way would be to check if the system can handle long paths.

**Comment by lawl** [comment] 2017-06-04 22:03
@PabloCastellano Do you want to report this upstream in ecryptfs that it has issues with special devices?

**Comment by ollieparanoid** [comment] 2017-06-04 23:46
@lawl: I have added ecryptfs to the [Troubleshooting](https://github.com/postmarketOS/pmbootstrap/wiki/Troubleshooting) wiki page. I don't think implementing a check for it is worth it right now, but if there are lots of users having this problem in the future, we should do it.

If we *do* implement a check, it should really check if /dev/random etc. work after creating them, instead of assuming, that if the filename length is limited, it must be ecryptfs (reminds me of these bad browser checks: if you can't do that, you must be browser xy).

**Comment by lawl** [comment] 2017-06-05 00:23
Ah well, I'm pretty preoccupied here. I think eCryptFS is a bad idea and it should die in a fire.

I'd rather just encrypt the entire partition with dm-crypt/LUKS and have none of these problems.

But I predict, more of these issues will surface. So let's just keep this open for now, since we know what the issue is, but we haven't resolved it yet.

(And no we can't do feature detection against filesystems, unfortunately. Personal opinion: eCryptFS is a pile of garbage that should't be supported, 'cause garbage. Again that's just **MY** opinion.)

**Comment by ollieparanoid** [comment] 2017-06-05 15:25
@PabloCastellano: Your ecryptfs issue seems to be solved now (that [newer version of eCryptFS seems to work](https://github.com/postmarketOS/pmbootstrap/issues/52#issuecomment-306180309)), and further steps are described in the [porting guide](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device). I see that you have already [created a device page](https://github.com/postmarketOS/pmbootstrap/wiki/motorola-titan-%28Moto-G-2014%29) and written down your porting status in the wiki.

Do you have any more questions? Otherwise we'd close this ticket (the porting status is already on the wiki page, and otherwise this ticket would get quite long - so better open up a new one for specific issues). Thanks for your porting efforts so far :)

**Comment by ollieparanoid** [comment] 2017-06-05 15:49
Closing, as discussed on IRC.

**Closed by ollieparanoid** 2017-06-05 15:49 UTC
Labels: need more info
