### ISSUE TITLE
Nexus 4 install help

### ISSUE THREAD

**Issue by Red5d** [postmarketOS/pmbootstrap#32] opened 2017-06-01 19:07 UTC
I've got a Nexus 4 (lg-mako) that I'd like to test this on (and try to fix some of the non-working items).

I managed to get an image built using pmbootstrap, though I had to switch the alpine sources to the v3.6 repos for a few things that weren't in the edge armhf repos yet.

When I tried to flash the image to my Nexus 4, the `pmbootstrap flasher flash_system` looked like it succeeded, but `pmbootstrap flasher flash_kernel` failed. I tried using `pmbootstrap flasher boot` to just boot the new kernel, and the phone just went to a blank screen and never did anything else.

Am I missing something?

Also, in the wiki where it says the device must be in "flashing mode", you actually mean rebooted to the bootloader, right?

**Comment by MartijnBraam** [comment] 2017-06-01 19:18
Flashing mode is the part where the fastboot commands work (bootloader)

What is the error you get from flash_kernel?

**Comment by lawl** [comment] 2017-06-01 19:47
> and the phone just went to a blank screen and never did anything else.

Did the phone register as a network adapter? Because you will need to enter the password you set to decrypt the root partition. Maybe the display only starts working after the root partition has been decrypted?

Check if you see a new network interface and if it's there, telnet into the phone and enter your password.

**Comment by ollieparanoid** [comment] 2017-06-01 21:10
I have not yet tested the kernel flashing with fastboot.

Blank screen is basically the same as it happens on my phone. The actual splash screen appears only for a short time. From the [introduction post](https://ollieparanoid.github.io/post/postmarketOS/#prototype):
> Generally speaking, the samsung-i9100 port works better than the lg-mako port. The latter has some strange driver bugs. **The boot splash images only appear for a second,** XWayland does not work there and the colors in Weston are all red. I even had to patch Weston before it worked at all. Without the patch it assumes it should draw with 0 Hz — in other words: Never ;) 

So as @lawl says, you should get an IP automatically on linux (dhcpcd is running on the phone). Then connect to the phone via `telnet 192.168.2.15` and type in the password.

After that, Wayland should start, and you should be able to connect via: `ssh user@192.168.2.15`.

**Comment by Red5d** [comment] 2017-06-02 01:13
Ah, ok. I forgot about the telnet part. I bet that was it.

I "zapped" the chroot after that to experiment with porting this to my OnePlus One, so I'm now trying to get the linux-lg-mako package to build again. I've tried both with and without the `gpu-msm-fix-gcc5-compile.patch` included and I'm getting hundreds of lines of build errors starting like this:

`>>> linux-lg-mako: Unpacking /var/cache/distfiles/linux-lg-mako-1495bfcf93f9e0e896331f29e1850387c31d6714.zip...
In file included from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/stddef.h:4:0,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/posix_types.h:4,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/types.h:17,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/thread_info.h:10,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/preempt.h:9,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/spinlock.h:50,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/mmzone.h:7,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/gfp.h:4,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/include/linux/mm.h:8,
                 from /home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/mm/rmap.c:45:
/home/user/build/src/lge-kernel-mako-1495bfcf93f9e0e896331f29e1850387c31d6714/mm/rmap.c:572:15: warning: 'is_vm_hugetlb_page' is static but used in inline function 'vma_address' which is not static
  if (unlikely(is_vm_hugetlb_page(vma)))`

Could modifications to the `config-lg-mako.armhf` file cause this, or would it more likely be a problem with the compiler? I previously enabled a few items in that kernel config with the `menuconfig` option (which seems to have broken now and the menu doesn't actually work).

**Comment by lawl** [comment] 2017-06-02 01:21
That's a warning, not an error message, so this is not the cause of the build failing. Looking at these takes a bit of practice and isn't exactly pleasant, especially if you compile with multiple cores. But try finding the `error:` or dump a more complete log on a pastebin somewhere.

**Comment by Red5d** [comment] 2017-06-02 01:46
Ok, here's the full output: https://pastebin.com/csPPayv3

I looked through and found the actual errors I think. Problems with the usb drivers? (lines 863-873 in the paste)

**Comment by lawl** [comment] 2017-06-02 01:55
what changes did you make to the kernel config?

**Comment by Red5d** [comment] 2017-06-02 03:07
Here's the git diff of the config file showing my changes: https://pastebin.com/38wHPV3n

I made several changes to enable module loading, various wifi drivers, some usb stuff, etc. I suppose I could try disabling some of the USB stuff I enabled and see if that resolves it.

**Comment by ollieparanoid** [comment] 2017-06-02 18:10
I recommend only changing few/one setting at a time, recompiling, checking if they work (on the device), and then versioning that change with git.
pmbootstrap makes use of ccache, so after the first compiling, all subsequent re-compiles should be much faster.
I had also tried to enable module loading at some point, and as far as I remember, it did not compile with that setting (but I didn't try hard to make that work).

**Comment by ollieparanoid** [comment] 2017-06-20 17:07
Closing. Please comment, if you feel that this should be discussed more.

**Closed by ollieparanoid** 2017-06-20 17:07 UTC
Labels: question
