### ISSUE TITLE
pmbootstrap install cp: write error: No space left on device [samsung-i9100]

### ISSUE THREAD

**Issue by montvid** [postmarketOS/pmbootstrap#975] opened 2017-12-04 07:53 UTC
Pmbootstrap does not finish the install command. GUI - none, I tried --no-fde, tried zap with the same error. Maybe it has something to do with the Alpine update - the files being too large for the 165mb image?

cp: write error: No space left on device
cp: can't create directory '/mnt/install/lib/udev': No space left on device
cp: can't create directory '/mnt/install/lib/device-mapper': No space left on device
cp: can't create directory '/mnt/install/lib/multipath': No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
(015798) [09:31:43] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(015798) [09:31:43] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/monika/.local/var/pmbootstrap/log.txt
(015798) [09:31:43] ERROR: Command failed: (native) % cd /mnt/rootfs_samsung-i9100 && cp -a efs bin srv run sbin root tmp dev etc sys usr boot mnt proc var media lib /mnt/install/
(015798) [09:31:43] Run 'pmbootstrap log' for details.
(015798) [09:31:43] See also: <https://postmarketos.org/troubleshooting>
(015798) [09:31:43] Traceback (most recent call last):
  File "/home/monika/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', "env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/monika/.local/var/pmbootstrap/chroot_native sh -c 'cd /mnt/rootfs_samsung-i9100;cp -a efs bin srv run sbin root tmp dev etc sys usr boot mnt proc var media lib /mnt/install/'"]' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/monika/pmbootstrap/pmb/__init__.py", line 59, in main
    getattr(frontend, args.action)(args)
  File "/home/monika/pmbootstrap/pmb/helpers/frontend.py", line 201, in install
    pmb.install.install(args)
  File "/home/monika/pmbootstrap/pmb/install/install.py", line 334, in install
    install_system_image(args)
  File "/home/monika/pmbootstrap/pmb/install/install.py", line 212, in install_system_image
    copy_files_from_chroot(args)
  File "/home/monika/pmbootstrap/pmb/install/install.py", line 90, in copy_files_from_chroot
    working_dir=mountpoint)
  File "/home/monika/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/monika/pmbootstrap/pmb/helpers/run.py", line 66, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /mnt/rootfs_samsung-i9100 && cp -a efs bin srv run sbin root tmp dev etc sys usr boot mnt proc var media lib /mnt/install/

(016651) [09:32:16] % tail -f /home/monika/.local/var/pmbootstrap/log.txt -n 60

**Comment by PureTryOut** [comment] 2017-12-04 09:25
Is that using a specific interface, say Plasma Mobile? Try making an Android recovery image and flashing that (`./pmbootstrap.py install --android-recovery-image` iirc), it works for me on the Sony Amami.

**Comment by montvid** [comment] 2017-12-04 10:17
No, no GUI, it errors on *** (4/5) FILL INSTALL BLOCKDEVICE ***

**Comment by ollieparanoid** [comment] 2017-12-04 19:58
Thanks for reporting! This is a duplicate of #928 actually, I'll write down some ideas how we can fix this.

**Closed by ollieparanoid** 2017-12-04 19:58 UTC
