### ISSUE TITLE
[Fedora 26] pmbootstrap install immediately fails

### ISSUE THREAD

**Issue by ke151** [postmarketOS/pmbootstrap#816] opened 2017-10-24 00:03 UTC
Hi all, having a (hopefully) easy to fix issue. My desktop running Fedora 26 almost immediately stops with an error message:
`ERROR: Command failed: % sudo /home/kyle/PmOS/Work/apk.static -U --root /home/kyle/PmOS/Work/chroot_native --cache-dir /home/kyle/PmOS/Work/cache_apk_x86_64 --initdb --arch x86_64 add alpine-base`

I managed to build successfully on my laptop running Arch. EDIT: I'm building for `lg-hammerhead` if that matters.

Troubleshooting steps I've tried, to no avail:
-Restarting computer after installing all available updates
-Waiting a few days and deleting `pmbootstrap` folder and re-cloning (also zapping all chroots regularly)
-Disabling `SELinux` temporarily

My hardware is nothing too exotic, AMD FX-4170, but it at least is faster than my laptop!

Here's the full log file: https://hastebin.com/osajinebok.rb

Happy to help with any attempts to debug, but anything too complex I'll need some fairly specific instructions as I'm much more a hobbyist than a "real" developer.

**Comment by drebrez** [comment] 2017-10-24 00:22
Looking at the log I noticed some certificate errors. Is the system datetime synchronized?

**Comment by ke151** [comment] 2017-10-24 01:02
Looks to be:
```
kyle@barad-dur pmbootstrap]$ timedatectl
Local time: Mon 2017-10-23 20:59:30 EDT
Universal time: Tue 2017-10-24 00:59:30 UTC
RTC time: Tue 2017-10-24 00:59:30
Time zone: America/New_York (EDT, -0400)
Network time on: yes
NTP synchronized: yes
RTC in local TZ: no
```

**Comment by PureTryOut** [comment] 2017-10-24 07:26
I have this error quite often, for me it's always resolved by just re-running the command.

I'm not exactly sure how to reproduce it, but I *think* for example after building a package (`build --force --strict`) right after having run an install `(install --no-fde`).

**Comment by ollieparanoid** [comment] 2017-10-24 15:21
Regarding Fedora, this is a duplicate of #722. It should work if you pass a HTTP mirror:
`pmbootstrap -m http://nl.alpinelinux.org/alpine/ ...`

(The packages are signed anyway, so that way more metadata is visible over the network, but the packages are still verified.)

@PureTryOut: that sounds like a different issue, maybe a network outage?

**Comment by ollieparanoid** [comment] 2017-10-24 15:25
Please do further Fedora related discussion in #722.

**Closed by ollieparanoid** 2017-10-24 15:25 UTC
Labels: duplicate
