### ISSUE TITLE
fails on ubuntu 17.10

### ISSUE THREAD

**Issue by computer777** [postmarketOS/pmbootstrap#834] opened 2017-10-27 20:16 UTC
https://pastebin.com/WjZrWJc3 -nexus 7 2012

what is your build environment or the OS you've had success on??

**Comment by ollieparanoid** [comment] 2017-10-27 20:49
Welcome to postmarketOS!

pmbootstrap uses qemu user mode emulation to execute arm binaries on an x86_64 computer. That relies on the "binfmt_misc" being set up correctly.

You might have another program installed, which sets up the binfmt_misc stuff in a way that is incompatible with pmbootstrap (e.g. different path to the qemu executable). That might have happened if you have tried to run stuff from a Raspberry Pi SD card for example. It might also be, that Ubuntu 17.10 does this by default.

Could you please try `./pmbootstrap.py shutdown` (and `./pmbootstrap.py zap` to remove the non working chroots it has created), then try it again?

pmbootstrap is known to be working on Alpine Linux, Arch Linux, Gentoo, older versions of Ubuntu, ... - so it should really be possible to get it working on 17.10, too.

**Comment by computer777** [comment] 2017-10-27 21:05
I have typed those two commands into the terminal and reran ./pmbootstrap.py install and it has not stopped building yet. At linux-asus-grouper...apk now. Your advice seems to have done the trick.
What information could i provide you to further assist?

**Comment by ollieparanoid** [comment] 2017-10-27 21:09
Glad to hear that! Besides whether the commands worked or not (which you've already answered):
* Do you have just installed Ubuntu (might be the case in a VM)?
* Are you aware of installing anything binfmt/qemu related at some point?

**Comment by computer777** [comment] 2017-10-27 21:28
1]Yes, my main OS is Ubuntu and just updated to 17.10 yesterday.
2]Yes, was curious, becuase it appeared similar to virtualbox - I do have AQEMU and the launcher installed.

**Comment by computer777** [comment] 2017-10-27 22:28
I figured it is not my job to close issues. 
Since there really isnt any issue here....
I am still having issues of my own with telnet/ssh. With FDE it takes a few tries with telnet and ssh password does not read back as correct. With FDE I get an orange screen with keyboard.
I figured to try without encryption and upon boot I am left with a black screen and my password is still unrecognized.

**Comment by ollieparanoid** [comment] 2017-10-27 22:35
> I figured it is not my job to close issues.

Well, you can close it if you fell like it is resolved. Someone will open it again if that person think otherwise.

I am not sure I understand what you are saying, you wrote "With FDE" twice. So unlocking does not work, it does not recognize your password?

And with `--no-fde` SSH login does not work?

*Consider joining the [chat](https://wiki.postmarketos.org/wiki/Matrix_and_IRC)!*

**Comment by computer777** [comment] 2017-10-27 22:57
I left it to build a few times with encryption and was not sure if it actually unlocked. Um, after the successful telnet session using ssh the  easiest password I could think of did not work.
I left it build without encryption and using ssh , the password again didn't work.

And, with encryption on - I was welcomed by an orange screen and an onscreen keyboard. With encryption off I was welcomed by a black screen.

**Comment by ollieparanoid** [comment] 2017-10-27 22:59
It sounds like, the video output is not working for some reason. Which user interface did you choose in `pmbootstrap init`?
For SSH, use the username you have specified in `pmbootstrap init` (default: `user`), and the password you assign to that user in `pmbootstrap install`. That should work, does it not?

**Comment by computer777** [comment] 2017-10-27 23:48
I chose xfce4.
I chose user for the username. The password, for me, does not work.

**Comment by ollieparanoid** [comment] 2017-10-27 23:53
Okay, xfce4 probably failed (maybe related to #779). You could debug this once you have ssh working, and you could use weston in the meantime which should work (if you want to try it out).
The password should be working, no one reported that it does not.
* Are you connecting to the right IP?
* Try to rebuild it with a very simple user password just to make sure, then flash it again and finally test it.

**Comment by computer777** [comment] 2017-10-28 00:24
Yes, sir. At least as far as I am aware. You're github lists the IP as 172.16.42.1. I believe, anyway, the IP is showing up as 172.16.42.2.
And, yes, the password I typed in was very simple.
I will, tomorrow, use Weston as the display. If you would like I will report back.

**Comment by ollieparanoid** [comment] 2017-10-28 00:33
That sounds like you have been connecting to `.2`? The target device's IP is `172.16.42.1`, the IP of your PC connected via USB to the device is `172.16.42.2`. So you would need: `ssh user@172.16.42.1`.
Yes, please report your progress. Thanks!

**Comment by computer777** [comment] 2017-10-28 14:28
OK, I am letting it build with hildon as the display. Meanwhile, finally connected via ssh using the proper address. My own misunderstanding and fault, obviously. 
Is there a how to for getting the display to start?

**Comment by drebrez** [comment] 2017-10-28 15:40
@computer777 for hildon, try with `apk add mesa-dri-swrast`, if you don't have internet on the device you can try with https://wiki.postmarketos.org/wiki/USB_Internet

**Comment by computer777** [comment] 2017-10-30 16:16
Finally able to see what PostMarketOS is all about with a flash of boot and system with Weston. I'm anxiously waiting for hildon or xfce4 to be usable.
Are there any updates you'd be willing to share for the grouper??

**Comment by ollieparanoid** [comment] 2017-10-30 21:25
I've added follow up pointers in the other thread regarding X11 and Hildon. What exactly do you mean with this?
> Are there any updates you'd be willing to share for the grouper??

**Comment by computer777** [comment] 2017-10-30 21:42
Yes, sorry for my poor word and phrase choices. I guess, i just mean progress, like, how far along the maintainer is with pmos stability for the device.
Also, idk, i think i cross posted. Sorry.
The xfce4 system.img/kernel combination for whatever reason leaves me without ssh access. Could it just be a faulty usb cable?? @ollieparanoid

**Comment by ollieparanoid** [comment] 2017-11-01 16:58
> how far along the maintainer is with pmos stability for the device.

I think all known progress is on the [device's wiki page](https://wiki.postmarketos.org/wiki/Google_Nexus_7_2012_(asus-grouper)). It hasn't seen an update since the maintainer @antonok-edm [since august](https://github.com/postmarketOS/pmbootstrap/wiki/asus-grouper-(Google-Nexus-7-2012)/_history) though, so maybe he isn't playing much with postmarketOS on that device anymore.

> The xfce4 system.img/kernel combination for whatever reason leaves me without ssh access. Could it just be a faulty usb cable?

Uh, maybe. You could try another USB cable and let us know if that doesn't help it, so we can debug further. The UI shouldn't have any influence on whether SSH works or not. The device page says "Can't boot without reflashing boot (!)". I'm not sure what this means, maybe booting only works directly after flashing a kernel to the boot partition, or after flashing the system partition?

If you have some time, I recommend that you play around with various combinations of flashing images and then trying to boot it. And write down what you have done, so you know which combinations work and which ones do not.

> Edit- does the git repository need to be cloned every couple days? There is a way to sync the repo without deleting anything, no?

Use `git pull` to update the source :)

**Comment by antonok-edm** [comment] 2017-11-01 20:27
@ollieparanoid @computer777 I'm still around :)

I've been fairly busy recently, but I'd still be happy to help out with the Nexus 7 2012 if I can. I haven't personally seen any SSH problems for a long time, but it's possible something has changed since the last time I tried. I can find some time in the next few days to try a new flash and report back.

> Can't boot without reflashing boot

By that, I'm referring to an issue I haven't seen anyone else having, where fully powering off the device and powering it on again would make it hang on the green Android bootloader screen. Reflashing the boot partition allows it to boot one more time. That issue should not be relevant as long as the device is not powered off.

**Comment by computer777** [comment] 2017-11-04 16:09
@antonok-edm  ,good news! You are still interested in working toward  a stable (regardless of my personal problems...) pmOS for grouper, then? Please keep me informed if it would not be a problem.

**Comment by computer777** [comment] 2017-11-04 16:13
@ollieparanoid it was just occurring for a short time somehow - beyond my comprehension. 
Yes, after letting pmOS build I used the two flasher commands from within /pmbootstrap.  I booted up and the OS would not load - whatever the exact error message was it was something about there being no boot image.

**Comment by ollieparanoid** [comment] 2017-11-04 16:21
So it is gone now? That sounds like the "can't find the boot partition" message, which would occur if you didn't flash the system image (which also contains the boot partition, see [partition layout](https://wiki.postmarketos.org/wiki/Partition-layout)) before booting a kernel.

**Comment by antonok-edm** [comment] 2017-11-07 13:56
Quick update - I am able to boot successfully and SSH into the device, but I find that it will sometimes hang a seemingly random amount of time shortly after booting -- perhaps this is what you were seeing, @computer777. You have to be quick to get a successful SSH. I haven't seen this problem before.

From the few times I've tested this so far, I have gotten it to not crash a few times (maybe 1 out of 4 or 5 tries). I'm going to see if I can get any more information than this -- so far it seems very random!

**Comment by ollieparanoid** [comment] 2017-11-18 14:06
In hindsight, I think it would have been better to open a new issue once the initial problem has been resolved - it's hard to see the actual problem now. But after reading through the thread, the "only problem" (not saying that it's a small issue 😉) is @antonok-edm reporting that booting crashes in about 1 of 5 times.

@antonok-edm and @computer777: if either of you can reproduce that problem (or other problems that are not in the tracker yet), please open up a new issue and link to this one if it is relevant.

Thanks!

**Closed by ollieparanoid** 2017-11-18 14:06 UTC
Labels: bug, need more info, pmbootstrap
