### ISSUE TITLE
pmbootstrap.py export loops after reboot

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#1351] opened 2018-03-20 12:07 UTC
If I run pmbootstrap.py export after restarting the system, it just loops:

pavel@duo:/data/l/pmos/pmbootstrap$ ./pmbootstrap.py export
[12:59:25] Update package index for armhf (4 file(s))
^CTraceback (most recent call last):
    package_providers = providers(args, package, arch, must_exist, indexes)
  File "/data/fast/l/pmos/pmbootstrap/pmb/parse/apkindex.py", line 303, in providers
    index_packages = parse(args, path)
  File "/data/fast/l/pmos/pmbootstrap/pmb/parse/apkindex.py", line 215, in parse
    block = parse_next_block(args, path, lines, start)
  File "/data/fast/l/pmos/pmbootstrap/pmb/parse/apkindex.py", line 65, in parse_next_block
    for i in range(start[0], len(lines)):
KeyboardInterrupt

On second try, 
pavel@duo:/data/l/pmos/pmbootstrap$ ./pmbootstrap.py export

it fails different way (probably because I interrupted the first run, let me try with re-running init/zap).

**Comment by pavelmachek** [comment] 2018-03-20 12:16
Doing pmbootstrap init/install fixes this.

**Comment by ollieparanoid** [comment] 2018-03-20 18:35
I can reproduce this. Looks like the dependency parsing loops over the same packages over and over for some reason, and when running pmbootstrap again (even with the same command) the isue is gone. This is possibly related to the APKINDEX files being downloaded the first time ("Update package index for armhf").

Thanks for reporting and sorry for the breakage!

**Comment by ollieparanoid** [comment] 2018-03-21 22:53
I understand the problem now:
* pmbootstrap parses the `armhf` APKINDEX and fills up the cache, with the parsed information and with the lastmodified date of the APKINDEX file.
* pmbootstrap notices that the APKINDEX file is out of date and updates it.
* when reading from the APKINDEX, the cache gets ignored because the lastmodified date is different.
* the cache does not get deleted and filled up again.
* this slows down the dependency resolving incredibly, so it looks like it's just stuck.

PR with a fix coming soon.

**Closed** 2018-03-24 16:31 UTC
Labels: bug, pmbootstrap
