### ISSUE TITLE
Nokia N900: touchscreen is "upside down"

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#1179] opened 2018-01-29 11:54 UTC
In xfce4, touchscreen is "upside down". It can be fixed with

```
xinput --set-prop --type=float "TSC200X touchscreen" "Coordinate Transformation Matrix"  1.10 0.00 -0.05  0.00 1.18 -0.10  0.00 0.00 1.00                      
xinput --set-prop --type=int "TSC200X touchscreen" "Evdev Axis Inversion" 0 1
```

(or similar). aports/device/device-nokia-n900/udev/90-touchscreen-dev.rules is included, is there anything else that is needed? @craftyguy  ?

**Comment by ollieparanoid** [comment] 2018-01-29 18:41
Duplicate of #961.
If you have the time, it would be awesome if you could try out the fix proposed in https://github.com/postmarketOS/pmbootstrap/issues/961#issuecomment-350319871 and make a PR for it.

**Closed by ollieparanoid** 2018-01-29 18:41 UTC
